### ISSUE TITLE
build mp4mux standalone

### ISSUE THREAD

**Issue by nickdesaulniers** [yurydelendik/rtmp.js#1]
I would like to use mp4mux separate from this library to package mp3 into mp4 containers.  If I try to build `src/mp4mux.ts` I can see it depends on `src/mp4iso.ts`, but `src/mp4iso.ts` depends on `Shumway.StringUtilities.utf8decode`.

**Comment by nickdesaulniers** [comment]
`tsc  -t ES5 --out muxie.js util.ts rtmp.js/src/mp4iso.ts rtmp.js/src/mp4mux.ts`

where util.ts is a neutered version of rtmp.js/src/util.js:

``` typescript
module Shumway.StringUtilities {
...
}
```

**Comment by yurydelendik** [comment]
d5732bdc5da7b1815ad29e1264fd30d67fc7b369 has an MP3 frame parser and example

**Comment by nickdesaulniers** [comment]
wow thanks Yury!
